# Generated by Django 4.1.3 on 2025-05-09 12:50

import common.model_fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import logistics.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(db_index=True, max_length=1024, verbose_name='Название')),
                ('address', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес')),
                ('latitude', common.model_fields.LatitudeField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('longitude', common.model_fields.LongitudeField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
                ('contractor_type', models.PositiveSmallIntegerField(choices=[(1, 'Транспортная компания'), (2, 'Экспедитор/диспетчер'), (3, 'Водитель')], verbose_name='Тип компании')),
                ('transport_owns_count', models.PositiveIntegerField(blank=True, help_text='Указывается при типе контрагента "Транспортная компания" ', null=True, verbose_name='Количество собственных Т/С')),
                ('avatar_or_company_logo', models.ImageField(blank=True, null=True, upload_to=logistics.models.contractor_storage, verbose_name='Селфи для аватара/Логотип компании')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'db_table': 'contractor',
            },
        ),
        migrations.CreateModel(
            name='LogisticsOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(db_index=True, max_length=1024, verbose_name='Название')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'На рассмотрении'), (2, 'Одобрено'), (3, 'Отклонено')], default=1, verbose_name='Статус предложения')),
                ('amount', common.model_fields.AmountField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость доставки')),
                ('shipping_date', models.DateTimeField(verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Предложение логиста',
                'verbose_name_plural': 'Предложения логистов',
                'db_table': 'logistic_offers',
            },
        ),
        migrations.CreateModel(
            name='TransportApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('shipping_address', models.CharField(blank=True, default='', max_length=1024, verbose_name='Адрес отгрузки')),
                ('shipping_latitude', common.model_fields.LatitudeField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта адреса отгрузки')),
                ('shipping_longitude', common.model_fields.LongitudeField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота адреса отгрузки')),
                ('delivery_address', models.CharField(blank=True, default='', max_length=1024, verbose_name='Адрес доставки')),
                ('delivery_latitude', common.model_fields.LatitudeField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта адреса доставки')),
                ('delivery_longitude', common.model_fields.LongitudeField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота адреса доставки')),
                ('sender', models.CharField(max_length=64, verbose_name='Отправитель')),
                ('recipient', models.CharField(max_length=64, verbose_name='Получатель')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Назначение логиста'), (2, 'Машина загружена'), (3, 'Машина выгружена'), (4, 'Окончательная приемка'), (5, 'Выполнена'), (6, 'Отменена')], default=1, verbose_name='Статус')),
                ('cargo_type', models.CharField(max_length=32, verbose_name='Характер груза')),
                ('loading_type', models.PositiveSmallIntegerField(choices=[(1, 'Зад'), (2, 'Бок'), (3, 'Верх')], verbose_name='Формат погрузки')),
                ('weight', models.FloatField(verbose_name='Вес (кг.)')),
                ('sender_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Номер телефона отправителя')),
                ('receiver_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Номер телефона получателя')),
                ('loading_hours', models.CharField(blank=True, default='', max_length=12, verbose_name='Часы погрузки')),
                ('weekend_work', models.BooleanField(default=False, verbose_name='Работа в выходные')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('shipping_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отгрузки')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата прибытия')),
                ('loaded_weight', models.FloatField(blank=True, help_text='Поле для справки, не влияет на расчет стоимости', null=True, verbose_name='Загруженный вес')),
                ('accepted_weight', models.FloatField(blank=True, help_text='Поле для справки, не влияет на расчет стоимости', null=True, verbose_name='Принятый вес')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_logistics_offer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.logisticsoffer', verbose_name='Выбранное предложение логиста')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Заявка на транспорт',
                'verbose_name_plural': 'Заявки на транспорт',
                'db_table': 'transport_applications',
            },
        ),
    ]
