# Generated by Django 4.1.3 on 2025-05-09 12:50

import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0001_initial'),
        ('company', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportapplication',
            name='created_by',
            field=models.ForeignKey(default=common.utils.get_current_user_id, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='transport_applications', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
        migrations.AddField(
            model_name='transportapplication',
            name='delivery_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_transport_app', to='company.city', verbose_name='Город доставки'),
        ),
        migrations.AddField(
            model_name='transportapplication',
            name='shipping_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_transport_app', to='company.city', verbose_name='Город отгрузки'),
        ),
        migrations.AddField(
            model_name='logisticsoffer',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='logistics.transportapplication'),
        ),
        migrations.AddField(
            model_name='logisticsoffer',
            name='chat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chat', verbose_name='Чат'),
        ),
        migrations.AddField(
            model_name='logisticsoffer',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.contractor', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='logisticsoffer',
            name='logist',
            field=models.ForeignKey(default=common.utils.get_current_user_id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractor',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='created_by',
            field=models.ForeignKey(default=common.utils.get_current_user_id, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
        migrations.AlterUniqueTogether(
            name='transportapplication',
            unique_together={('object_id', 'content_type')},
        ),
    ]
