# Generated by Django 4.1.3 on 2025-05-09 12:50

import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_initial'),
        ('product', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('exchange', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_by',
            field=models.ForeignKey(default=common.utils.get_current_user_id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recyclablesdeal',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='exchange.recyclablesapplication', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='recyclablesdeal',
            name='buyer_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recyclables_buy_deals', to='company.company', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='recyclablesdeal',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='chat.chat', verbose_name='Чат сделки'),
        ),
        migrations.AddField(
            model_name='recyclablesdeal',
            name='created_by',
            field=models.ForeignKey(default=common.utils.get_current_user_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='recyclables_deals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший сделку'),
        ),
        migrations.AddField(
            model_name='recyclablesdeal',
            name='delivery_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_recyclables_deal', to='company.city', verbose_name='Город доставки'),
        ),
        migrations.AddField(
            model_name='recyclablesdeal',
            name='shipping_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_recyclables_deal', to='company.city', verbose_name='Город отгрузки'),
        ),
        migrations.AddField(
            model_name='recyclablesdeal',
            name='supplier_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recyclables_sell_deals', to='company.company', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='recyclablesapplication',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='recyclablesapplication',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recyclables_applications', to='company.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='recyclablesapplication',
            name='recyclables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='product.recyclables', verbose_name='Вторсырье'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента'),
        ),
        migrations.AddField(
            model_name='equipmentdeal',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='exchange.equipmentapplication', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='equipmentdeal',
            name='buyer_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_buy_deals', to='company.company', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='equipmentdeal',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_deal', to='chat.chat', verbose_name='Чат сделки'),
        ),
        migrations.AddField(
            model_name='equipmentdeal',
            name='created_by',
            field=models.ForeignKey(default=common.utils.get_current_user_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_deals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший сделку'),
        ),
        migrations.AddField(
            model_name='equipmentdeal',
            name='delivery_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_equipment_deal', to='company.city', verbose_name='Город доставки'),
        ),
        migrations.AddField(
            model_name='equipmentdeal',
            name='shipping_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_equipment_deal', to='company.city', verbose_name='Город отгрузки'),
        ),
        migrations.AddField(
            model_name='equipmentdeal',
            name='supplier_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_sell_deals', to='company.company', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='equipmentapplication',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='category_applications', to='product.equipmentcategory', verbose_name='Категория оборудование'),
        ),
        migrations.AddField(
            model_name='equipmentapplication',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='equipmentapplication',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_applications', to='company.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='equipmentapplication',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_applications', to='product.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента'),
        ),
        migrations.AddIndex(
            model_name='imagemodel',
            index=models.Index(fields=['content_type', 'object_id'], name='images_content_d1d020_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmodel',
            index=models.Index(fields=['content_type', 'object_id'], name='documents_content_7d700d_idx'),
        ),
    ]
