# Generated by Django 4.1.3 on 2025-05-09 12:50

import colorfield.fields
import common.model_fields
import company.models
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(db_index=True, max_length=1024, verbose_name='Название')),
                ('latitude', common.model_fields.LatitudeField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('longitude', common.model_fields.LongitudeField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(db_index=True, max_length=1024, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('address', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес')),
                ('latitude', common.model_fields.LatitudeField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('longitude', common.model_fields.LongitudeField(blank=True, decimal_places=15, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
                ('image', models.ImageField(blank=True, null=True, upload_to=company.models.company_storage, verbose_name='Фото/логотип')),
                ('inn', models.CharField(blank=True, db_index=True, max_length=32, unique=True, verbose_name='ИНН')),
                ('bic', models.CharField(blank=True, max_length=15, null=True, verbose_name='БИК')),
                ('payment_account', models.CharField(blank=True, max_length=32, null=True, verbose_name='Расчетный счет')),
                ('correction_account', models.CharField(blank=True, max_length=32, null=True, verbose_name='Корресп. счет')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование банка')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Не проверенная'), (2, 'Проверенная'), (3, 'Надежная'), (4, 'Ненадёжная')], default=1, verbose_name='Статус')),
                ('head_full_name', models.CharField(max_length=100, null=True, verbose_name='ФИО директора')),
                ('staff', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('with_nds', models.BooleanField(default=False, verbose_name='С НДС')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Электронная почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('activity', models.PositiveSmallIntegerField(choices=[(1, 'Поставщик'), (2, 'Переработчик'), (3, 'Покупатель')], verbose_name='Вид деятельности')),
            ],
            options={
                'verbose_name': 'Виды деятельности компании',
                'verbose_name_plural': 'Виды деятельности компаний',
                'db_table': 'company_activity_types',
            },
        ),
        migrations.CreateModel(
            name='CompanyAdditionalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('contact_type', models.PositiveSmallIntegerField(choices=[(1, 'Телефон'), (2, 'Электронная почта'), (3, 'Whatsapp'), (4, 'Telegram')], verbose_name='Тип')),
                ('value', models.CharField(max_length=32, verbose_name='Контакт')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Контакт компании',
                'verbose_name_plural': 'Контакты компаний',
                'db_table': 'company_contacts',
            },
        ),
        migrations.CreateModel(
            name='CompanyAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(db_index=True, max_length=1024, verbose_name='Название')),
                ('activity', models.PositiveSmallIntegerField(choices=[(1, 'Поставщик'), (2, 'Переработчик'), (3, 'Покупатель')], verbose_name='Вид деятельности')),
            ],
            options={
                'verbose_name': 'Преимущество компании',
                'verbose_name_plural': 'Преимущества компании',
                'db_table': 'company_advantages',
            },
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('doc_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Устав'), (2, 'Реквизиты'), (3, 'ИНН')], null=True, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to=company.models.company_storage, verbose_name='Документ')),
                ('comment', models.CharField(blank=True, default='', max_length=64, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Документ компании',
                'verbose_name_plural': 'Документы компаний',
                'db_table': 'company_documents',
            },
        ),
        migrations.CreateModel(
            name='CompanyRecyclables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'Покупаю'), (2, 'Продаю')], default=1, verbose_name='Действие')),
                ('monthly_volume', models.FloatField(verbose_name='Примерный ежемесячный объем')),
                ('price', common.model_fields.AmountField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тип вторсырья компании',
                'verbose_name_plural': 'Типы вторсырья компаний',
                'db_table': 'company_recyclables',
            },
        ),
        migrations.CreateModel(
            name='CompanyVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Новая'), (2, 'Проверенная'), (3, 'Надежная'), (4, 'Отклонена')], default=1, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Заявка на верификацию',
                'verbose_name_plural': 'Заявки на верификацию',
                'db_table': 'company_verification_requests',
                'ordering': ['-created_at'],
                'get_latest_by': '-created_at',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(db_index=True, max_length=1024, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Округ',
                'verbose_name_plural': 'Округи',
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='EquipmentProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('special_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Предложение по оборудованию',
                'verbose_name_plural': 'Предложения по оборудованию',
                'db_table': 'equipments_proposals',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('special_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'db_table': 'proposals',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(db_index=True, max_length=1024, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Эконом'), (2, 'Стандартный'), (3, 'Расширенный'), (4, 'Абсолют')], default=1, verbose_name='Подписки')),
                ('period', models.PositiveSmallIntegerField(choices=[(1, 'Месяц'), (2, '3 Месяца'), (3, '6 Месяцев'), (4, 'Год')], default=1, verbose_name='Период подписки')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена подписки')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'db_table': 'subscribes',
            },
        ),
        migrations.CreateModel(
            name='SubscribesCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('time_end', models.DateTimeField(verbose_name='Дата окончания подписки')),
                ('time_begin', models.DateTimeField(verbose_name='Дата начала подписки')),
                ('payment_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер платежа')),
                ('payment_access', models.BooleanField(blank=True, default=False, null=True, verbose_name='Успешность платежа')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('subscribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.subscribe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subscribe',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='companies_subscribes', through='company.SubscribesCompanies', to='company.company', verbose_name='Подписки компаний'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(db_index=True, max_length=1024, verbose_name='Название')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions_district', to='company.district', verbose_name='Округ')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='RecyclingCollectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Помечен как удаленный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(db_index=True, max_length=1024, verbose_name='Название')),
                ('activity', models.PositiveSmallIntegerField(choices=[(1, 'Поставщик'), (2, 'Переработчик'), (3, 'Покупатель')], verbose_name='Вид деятельности')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'verbose_name': 'Тип сбора/переработки',
                'verbose_name_plural': 'Типы сбора/переработки',
                'db_table': 'recycling_collection_types',
                'unique_together': {('name', 'activity')},
            },
        ),
    ]
