# Generated by Django 4.1.3 on 2025-05-09 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='applications', to='exchange.recyclablesapplication', verbose_name='Заявки из рассылок'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='companies', to='company.company', verbose_name='Компании из рассылок'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='sender_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='company.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='equipmentproposal',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='equipments_applications', to='exchange.equipmentapplication', verbose_name='Заявки из рассылок'),
        ),
        migrations.AddField(
            model_name='equipmentproposal',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='equipments_companies', to='company.company', verbose_name='Компании из рассылок'),
        ),
        migrations.AddField(
            model_name='equipmentproposal',
            name='sender_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_proposals', to='company.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='companyverificationrequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='company.company', verbose_name='Компания'),
        ),
    ]
