# Generated by Django 4.1.3 on 2025-05-09 12:50

import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyverificationrequest',
            name='employee',
            field=models.ForeignKey(default=common.utils.get_current_user_id, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='companyrecyclables',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recyclables', to='company.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='companyrecyclables',
            name='recyclables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.recyclables', verbose_name='Вторсырье'),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='company.company', verbose_name='Компания'),
        ),
        migrations.AlterUniqueTogether(
            name='companyadvantage',
            unique_together={('name', 'activity')},
        ),
        migrations.AddField(
            model_name='companyadditionalcontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='company.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='companyactivitytype',
            name='advantages',
            field=models.ManyToManyField(blank=True, to='company.companyadvantage', verbose_name='Преимущества компании'),
        ),
        migrations.AddField(
            model_name='companyactivitytype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_types', to='company.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='companyactivitytype',
            name='rec_col_types',
            field=models.ManyToManyField(blank=True, to='company.recyclingcollectiontype', verbose_name='Тип сбора/переработки'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='company',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 5}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='my_company', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.region', verbose_name='Район'),
        ),
    ]
