# Generated by Django 4.1.3 on 2025-05-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='кол-во заявок'),
        ),
    ]
