# Generated by Django 4.1.3 on 2025-05-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_subscribe_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='staff_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='кол-во сотрудников'),
        ),
    ]
