# Generated by Django 4.1.3 on 2025-05-13 11:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_subscribe_staff_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='suspend_staff',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
